# Python Homework (NumPy, Pandas)

**Note**: You can create a Python file or a Jupyter Notebook file

<br>

<ins>Use markdown formatting for the following questions (e.g., bold lettering, bullet points, different font sizes, etc.)</ins>: 

1. What does Pandas stand for?

    • PAN - Panel
    • DA - Data
    • S - system (or a plural "s" from panel data sets)
    - Or an open-source Python programming library specifically designed for data manipulation and analysis.

2. What are the 2 collections used in Pandas?

    - Series and the DataFrame

3. Name 4 things Pandas can do for us.

    - Read and write files
    - Clean missing or duplicate Date
    - Group and summarize data
    - Merge and join data 

4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?

In [ ]:
df.sort_values(by='column_name', inplace=True)

5. What is a CSV?

    - "Comma-Seperated Values" Each line of the file represents a single row of data.

6. When cleaning data what values do we not like in our data?

    - Missing or Null values (Nan, None, null)
    - Duplicate values
    - Outliers and extreme values or unrealistic
    - Mismatched or inconsistent formats
    - Incorrect data types or structural errors

#### **Please Complete this Coding Exercise:**

7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`
8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20
9. Make a Deep Copy of the above array
10. Concatenate these 3 arrays into a new array named 'newArray'...
    ```python

In [14]:
# 7
import numpy as np

array_7 = np.array([25, 16, 11, 2, 13, 4, 7, 81, 5, 6, 11, 12]).reshape(2, 3, 2)
print(array_7)

# 8
array_8 = np.linspace(0, 20, 6)
print(array_8)

# 9
array_9 = array_8.copy()

# 10
newArray = np.concatenate((array_7.flatten(), array_8, array_9))
print(newArray)

#([[25, 16]])
#([[11, 2], [13, 4]])
#([[7, 81], [5, 6], [11, 12]])

[[[25 16]
  [11  2]
  [13  4]]

 [[ 7 81]
  [ 5  6]
  [11 12]]]
[ 0.  4.  8. 12. 16. 20.]
[25. 16. 11.  2. 13.  4.  7. 81.  5.  6. 11. 12.  0.  4.  8. 12. 16. 20.
  0.  4.  8. 12. 16. 20.]


11. Sort 'newArray' in order into 'sortedArray'
12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.
13. Combined and sort the following arrays into one called 'comboArray' ...

In [23]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

# 11
sortedArray = np.sort(newArray)
print(sortedArray)

# 12
reshapedArray = sortedArray.reshape(4, 6)

row_one, row_two, row_three, row_four = reshapedArray

# Print 4 variables
print("First Row: ", row_one)
print("Second Row:", row_two)
print("Third Row: ", row_three)
print("Fourth Row:", row_four)

# 13
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

# Combine
comboArray = np.sort(np.concatenate((one, two, three)))
print(comboArray)


[ 0.  0.  2.  4.  4.  4.  5.  6.  7.  8.  8. 11. 11. 12. 12. 12. 13. 16.
 16. 16. 20. 20. 25. 81.]
First Row:  [0. 0. 2. 4. 4. 4.]
Second Row: [ 5.  6.  7.  8.  8. 11.]
Third Row:  [11. 12. 12. 12. 13. 16.]
Fourth Row: [16. 16. 20. 20. 25. 81.]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element.


In [27]:
sec1 = comboArray[1]
print("sec1:", sec1)

sec2 = comboArray[2:]
print("sec2:", sec2)

sec3 = comboArray[3:14]
print("sec3:", sec3)

sec4 = comboArray[-6:]
print("sec4:", sec4)

sec5 = comboArray[:-8]
print("sec5:", sec5)

sec6 = comboArray[16::2]
print("sec6:", sec6)

sec7 = comboArray[::-5]
print("sec7:", sec7)


sec1: 1
sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [ 3  4  5  6  7 10 11 12 13 14 15]
sec4: [22 23 24 25 26 27]
sec5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17]
sec6: [20 22 24 26]
sec7: [27 22 15 10  3]


15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object

In [ ]:
import pandas as pd

# Columns 
ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"])
quantity = pd.Series([4, 1, 2, 1])
unit = pd.Series(["cups", "cup", "large", "can"])

# Combine
df = pd.DataFrame({
    "Ingredients": ingredients,
    "Quantity": quantity,
    "Unit": unit
})

# Display
print(df)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


### Or ###

In [ ]:
import pandas as pd

data = {
    "Ingredients": pd.Series(["Flour", "Milk", "Eggs", "Spam"], index=[0, 1, 2, 3]),
    "Quantity": pd.Series([4, 1, 2, 1], index=[0, 1, 2, 3]),
    "Unit": pd.Series(["cups", "cup", "large", "can"], index=[0, 1, 2, 3])
}

dinner_df = pd.DataFrame(data)
print(dinner_df)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


16. Take this data and create a DataFrame named studentData
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
    ```
17. Add a new column to the DataFrame with the following deserts:
        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [ ]:
import pandas as pd

# 16. Create the DataFrame named studentData
data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}
studentData = pd.DataFrame(data)

# 17. Add a new column named 'Desserts'
studentData['Desserts'] = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

# 18. Sort by 'Name' and then 'address' in Ascending order
# 'janusha' will sort after uppercase names because python sorting is case-sensetive
studentData.sort_values(by=['Name', 'address'], ascending=True, inplace=True)

# Display the final sorted DataFrame
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

In [4]:

import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')

# To show where my file went.
import os

print(os.path.abspath('cows_and_goats.csv'))
print(pd.read_csv('cows_and_goats.csv', index_col=0))  

c:\Users\Blake Evans\Code\Savvycoder\Homework\cows_and_goats.csv
        Cows  Goats
Year 1    12     22
Year 2    20     19


20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

<br>


In [ ]:
import pandas as pd

veggies = pd.DataFrame({
    'Vegetable': ['Carrot', 'Broccoli', 'Spinach', 'Potato'],
    'Color': ['Orange', 'Green', 'Green', 'Brown'],
    'Price': [1.20, 2.50, 3.00, 0.90]
})

veggies.to_csv('vegetables.csv', index=False)
veggies

df = pd.read_csv('vegetables.csv')

df.loc[df['Vegetable'] == 'Potato', 'Price'] = 1.10   # the change

df.to_csv('vegetables_updated.csv', index=False)

# Just to show the path
import os

print(os.path.abspath('vegetables.csv'))
print(os.path.abspath('vegetables_updated.csv'))

print(os.path.exists('vegetables.csv'))          # True if saved
print(os.path.exists('vegetables_updated.csv'))  # True if saved
df

c:\Users\Blake Evans\Code\Savvycoder\Homework\vegetables.csv
c:\Users\Blake Evans\Code\Savvycoder\Homework\vegetables_updated.csv
True
True


,Vegetable,Color,Price
0,Carrot,Orange,1.2
1,Broccoli,Green,2.5
2,Spinach,Green,3.0
3,Potato,Brown,1.1


#### When done with homework:
- **Due Date**: The following Monday before class
- Make sure your homework file is well named
- Add the homework to your Homework repo
- Use  `git add .`, `git commit -m "message"`, and `git push` to upload your homework changes to GitHub in the cloud
- Create a JIRA ticket to indicate that your Homework is ready for review:
    - <ins> In the "Summary" box</ins>: Include First Name and Last Initial, plus a short description in the Summary box (Ex: Jane D. Week # Homework Complete)
    - <ins> In the "Description" box</ins>: Include GitHub repo url 

<br>